[2024-12-01T02:16:12.178+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: show_test_dir.Remove_directory scheduled__2024-11-24T00:00:00+00:00 [queued]>
[2024-12-01T02:16:12.192+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: show_test_dir.Remove_directory scheduled__2024-11-24T00:00:00+00:00 [queued]>
[2024-12-01T02:16:12.193+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-12-01T02:16:12.209+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Remove_directory> on 2024-11-24 00:00:00+00:00
[2024-12-01T02:16:12.212+0000] {standard_task_runner.py:60} INFO - Started process 114 to run task
[2024-12-01T02:16:12.216+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'show_test_dir', 'Remove_directory', 'scheduled__2024-11-24T00:00:00+00:00', '--job-id', '5996', '--raw', '--subdir', 'DAGS_FOLDER/Remove_test_dir.py', '--cfg-path', '/tmp/tmp8rtd3lid']
[2024-12-01T02:16:12.219+0000] {standard_task_runner.py:88} INFO - Job 5996: Subtask Remove_directory
[2024-12-01T02:16:12.280+0000] {task_command.py:423} INFO - Running <TaskInstance: show_test_dir.Remove_directory scheduled__2024-11-24T00:00:00+00:00 [running]> on host 4f673f93eb11
[2024-12-01T02:16:12.367+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='show_test_dir' AIRFLOW_CTX_TASK_ID='Remove_directory' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-24T00:00:00+00:00'
[2024-12-01T02:16:12.369+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-01T02:16:12.370+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rmdir /opt/***/dags/test_dir']
[2024-12-01T02:16:12.379+0000] {subprocess.py:86} INFO - Output:
[2024-12-01T02:16:12.380+0000] {subprocess.py:93} INFO - rmdir: failed to remove '/opt/***/dags/test_dir': No such file or directory
[2024-12-01T02:16:12.381+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-01T02:16:12.387+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-01T02:16:12.388+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=show_test_dir, task_id=Remove_directory, execution_date=20241124T000000, start_date=20241201T021612, end_date=20241201T021612
[2024-12-01T02:16:12.393+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5996 for task Remove_directory (Bash command failed. The command returned a non-zero exit code 1.; 114)
[2024-12-01T02:16:12.398+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-01T02:16:12.422+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
