[2024-11-24T05:25:08.665+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_test_dir.Make_directory manual__2024-11-24T05:25:07.891633+00:00 [queued]>
[2024-11-24T05:25:08.671+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_test_dir.Make_directory manual__2024-11-24T05:25:07.891633+00:00 [queued]>
[2024-11-24T05:25:08.672+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-11-24T05:25:08.685+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Make_directory> on 2024-11-24 05:25:07.891633+00:00
[2024-11-24T05:25:08.696+0000] {standard_task_runner.py:60} INFO - Started process 1382 to run task
[2024-11-24T05:25:08.704+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_test_dir', 'Make_directory', 'manual__2024-11-24T05:25:07.891633+00:00', '--job-id', '5911', '--raw', '--subdir', 'DAGS_FOLDER/directory.py', '--cfg-path', '/tmp/tmpsvoku5m3']
[2024-11-24T05:25:08.712+0000] {standard_task_runner.py:88} INFO - Job 5911: Subtask Make_directory
[2024-11-24T05:25:08.754+0000] {task_command.py:423} INFO - Running <TaskInstance: create_test_dir.Make_directory manual__2024-11-24T05:25:07.891633+00:00 [running]> on host 70a89d0d486b
[2024-11-24T05:25:08.807+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_test_dir' AIRFLOW_CTX_TASK_ID='Make_directory' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T05:25:07.891633+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T05:25:07.891633+00:00'
[2024-11-24T05:25:08.808+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-24T05:25:08.809+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir /opt/***/dags/test_dir']
[2024-11-24T05:25:08.816+0000] {subprocess.py:86} INFO - Output:
[2024-11-24T05:25:08.818+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/***/dags/test_dir’: File exists
[2024-11-24T05:25:08.819+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-24T05:25:08.826+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-24T05:25:08.829+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=create_test_dir, task_id=Make_directory, execution_date=20241124T052507, start_date=20241124T052508, end_date=20241124T052508
[2024-11-24T05:25:08.836+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5911 for task Make_directory (Bash command failed. The command returned a non-zero exit code 1.; 1382)
[2024-11-24T05:25:08.852+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-24T05:25:08.865+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
