[2024-11-24T05:26:09.252+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_test_dir.Make_directory manual__2024-11-24T05:25:07.891633+00:00 [queued]>
[2024-11-24T05:26:09.259+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_test_dir.Make_directory manual__2024-11-24T05:25:07.891633+00:00 [queued]>
[2024-11-24T05:26:09.260+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-11-24T05:26:09.269+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Make_directory> on 2024-11-24 05:25:07.891633+00:00
[2024-11-24T05:26:09.272+0000] {standard_task_runner.py:60} INFO - Started process 1401 to run task
[2024-11-24T05:26:09.275+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_test_dir', 'Make_directory', 'manual__2024-11-24T05:25:07.891633+00:00', '--job-id', '5912', '--raw', '--subdir', 'DAGS_FOLDER/directory.py', '--cfg-path', '/tmp/tmp8u157vfh']
[2024-11-24T05:26:09.276+0000] {standard_task_runner.py:88} INFO - Job 5912: Subtask Make_directory
[2024-11-24T05:26:09.310+0000] {task_command.py:423} INFO - Running <TaskInstance: create_test_dir.Make_directory manual__2024-11-24T05:25:07.891633+00:00 [running]> on host 70a89d0d486b
[2024-11-24T05:26:09.378+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_test_dir' AIRFLOW_CTX_TASK_ID='Make_directory' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T05:25:07.891633+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T05:25:07.891633+00:00'
[2024-11-24T05:26:09.379+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-24T05:26:09.380+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir /opt/***/dags/test_dir']
[2024-11-24T05:26:09.385+0000] {subprocess.py:86} INFO - Output:
[2024-11-24T05:26:09.387+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/***/dags/test_dir’: File exists
[2024-11-24T05:26:09.387+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-24T05:26:09.393+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-24T05:26:09.394+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=create_test_dir, task_id=Make_directory, execution_date=20241124T052507, start_date=20241124T052609, end_date=20241124T052609
[2024-11-24T05:26:09.400+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5912 for task Make_directory (Bash command failed. The command returned a non-zero exit code 1.; 1401)
[2024-11-24T05:26:09.415+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-24T05:26:09.427+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
