[2024-11-24T05:05:37.792+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_test_dir.Show_directory scheduled__2021-09-17T00:00:00+00:00 [queued]>
[2024-11-24T05:05:37.809+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_test_dir.Show_directory scheduled__2021-09-17T00:00:00+00:00 [queued]>
[2024-11-24T05:05:37.811+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-11-24T05:05:37.829+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Show_directory> on 2021-09-17 00:00:00+00:00
[2024-11-24T05:05:37.839+0000] {standard_task_runner.py:60} INFO - Started process 728 to run task
[2024-11-24T05:05:37.849+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_test_dir', 'Show_directory', 'scheduled__2021-09-17T00:00:00+00:00', '--job-id', '5789', '--raw', '--subdir', 'DAGS_FOLDER/directory.py', '--cfg-path', '/tmp/tmpyn5tadik']
[2024-11-24T05:05:37.853+0000] {standard_task_runner.py:88} INFO - Job 5789: Subtask Show_directory
[2024-11-24T05:05:37.913+0000] {task_command.py:423} INFO - Running <TaskInstance: create_test_dir.Show_directory scheduled__2021-09-17T00:00:00+00:00 [running]> on host 70a89d0d486b
[2024-11-24T05:05:37.982+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_test_dir' AIRFLOW_CTX_TASK_ID='Show_directory' AIRFLOW_CTX_EXECUTION_DATE='2021-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-17T00:00:00+00:00'
[2024-11-24T05:05:37.985+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-24T05:05:37.987+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'ls test_dir ']
[2024-11-24T05:05:37.996+0000] {subprocess.py:86} INFO - Output:
[2024-11-24T05:05:38.000+0000] {subprocess.py:93} INFO - ls: cannot access 'test_dir': No such file or directory
[2024-11-24T05:05:38.004+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-24T05:05:38.033+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-24T05:05:38.039+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=create_test_dir, task_id=Show_directory, execution_date=20210917T000000, start_date=20241124T050537, end_date=20241124T050538
[2024-11-24T05:05:38.079+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5789 for task Show_directory (Bash command failed. The command returned a non-zero exit code 2.; 728)
[2024-11-24T05:05:38.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-24T05:05:38.143+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
